name: Build and Release

on:
  release:
    types:
      - published  # Runs when a release is created or published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v4

      # Step 2: Set up Java 8
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      # Step 3: Install Python 3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 4: Verify Docker is available
      - name: Verify Docker
        run: docker --version

      # Step 5: Cache Maven dependencies
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 6: Extract version from pom.xml
      - name: Extract provider version
        id: get_version
        run: |
          VERSION=$(xmllint --xpath "string(//project/properties/provider.version)" pom.xml)
          echo "Provider version detected: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 7: Build project using Maven
      - name: Build with Maven
        run: mvn package -PcollectDependencies -Duser.id=$(id -u)

      # Optional: Debug to confirm output file exists
      - name: List target directory
        run: ls -lh target

      # Step 8: Upload build artifact to GitHub release
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/phpIPAMv${{ env.VERSION }}.zip  # Uses environment variable
          asset_name: phpIPAMv${{ env.VERSION }}.zip
          asset_content_type: application/zip